# Generated by Django 2.1.5 on 2019-02-13 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=1000)),
            ],
            options={
                'db_table': 'portscan_collect',
            },
        ),
        migrations.CreateModel(
            name='Configure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scantime', models.IntegerField(choices=[(1, '1 day'), (2, '2 day'), (3, '3 day'), (4, '4 day'), (5, '5 day'), (6, '6 day'), (7, '7 day'), (14, '2 weeks'), (21, '3 weeks'), (30, '1 month')], default=1, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Ip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'portscan_ip',
            },
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.IntegerField(unique=True)),
            ],
            options={
                'ordering': ('port',),
            },
        ),
        migrations.CreateModel(
            name='PortState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_date', models.DateTimeField(blank=True)),
                ('last_scan_date', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subnet',
            fields=[
                ('ip_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portscan.Ip')),
                ('subnetmask', models.IntegerField(blank=True, null=True)),
                ('start_ip', models.CharField(blank=True, max_length=1000)),
                ('end_ip', models.CharField(blank=True, max_length=1000)),
                ('excel_file', models.FileField(blank=True, max_length=1000, upload_to='')),
            ],
            bases=('portscan.ip',),
        ),
        migrations.AddField(
            model_name='portstate',
            name='ip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portscan.Ip'),
        ),
        migrations.AddField(
            model_name='portstate',
            name='port',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portscan.Port'),
        ),
        migrations.AddField(
            model_name='port',
            name='port_state',
            field=models.ManyToManyField(through='portscan.PortState', to='portscan.Ip'),
        ),
        migrations.AddField(
            model_name='ip',
            name='collect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portscan.Collect'),
        ),
    ]
