# Generated by Django 2.1.5 on 2019-03-25 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('scanday', models.IntegerField(blank=True, default=0)),
                ('scanhour', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CollectPort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.IntegerField()),
                ('collect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portscan.Collect')),
            ],
            options={
                'ordering': ('port',),
            },
        ),
        migrations.CreateModel(
            name='Configure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanday', models.IntegerField(default=0, unique=True)),
                ('scanhour', models.IntegerField(default=0, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Ip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=1000)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('collect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portscan.Collect')),
            ],
        ),
        migrations.CreateModel(
            name='IpPort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.IntegerField()),
                ('ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portscan.Ip')),
            ],
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.IntegerField(unique=True)),
            ],
            options={
                'ordering': ('port',),
            },
        ),
        migrations.CreateModel(
            name='PortState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.IntegerField()),
                ('openning', models.BooleanField(default=True)),
                ('scan_date', models.DateTimeField(blank=True)),
                ('last_scan_date', models.DateTimeField(blank=True)),
                ('ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portscan.Ip')),
            ],
        ),
    ]
